### ISSUE TITLE
Mapbox API fails for a custom dev token

### ISSUE THREAD

**Issue by serso** [boolder-org/boolder-rails#33]
Hey, I've added a new token to my Mapbox account and updated the `.env` file as instructed in `README.md`.
However, I'm getting `{"message":"Style not found"}` responses for `https://api.mapbox.com/styles/v1/nmondollot/cl95n147u003k15qry7pvfmq2?access_token=XXX` requests when running the server locally.
What am I doing wrong?

**Comment by nmondollot** [comment]
Hello Sergey,
I just changed the map access to public, so it should work now. 
Make sure you clear your browser's cache (or try with incognito mode).

Let me know if it works!

And feel free to reach out if you have any questions/remarks on the project!
