### ISSUE TITLE
Admin: show menu on mobile

### ISSUE THREAD

**Issue by nmondollot** [boolder-org/boolder-rails#36]
The admin menu is currently hidden on mobile, which is annoying.

[http://localhost:3000/fr/admin](http://localhost:3000/fr/admin)

Let's make it visible.

<img width="575" alt="Capture d’écran 2024-05-11 à 09 07 39" src="https://github.com/boolder-org/boolder-rails/assets/330823/c2c0a4e4-f2ef-42f0-8e25-515c4a043d05">

**Comment by kljuni** [comment]
The idea is to show the logo, 'Areas', 'Contribute' and also the search bar or without it?
![image](https://github.com/boolder-org/boolder-rails/assets/51400009/edda9e44-c083-42fa-9954-efb7f4e61a11)

**Comment by nmondollot** [comment]
We want to be able to search but it doesn't have to be a search bar
It can be a search icon (like on boolder.com)

Maybe we need to use a hamburger menu?

FYI I used code from tailwindui.com

**Comment by kljuni** [comment]
I add a search icon like on boolder.com for it to be consistent.
