### ISSUE TITLE
Can't connect to new CDN url

### ISSUE THREAD

**Issue by sanderdlm** [boolder-org/boolder-rails#51]
Since f622a1ed34b20edf678553c654cb9039200cf639, Boolder on the web looks like this for me:
<img width="1728" alt="Screenshot 2024-07-22 at 10 15 15" src="https://github.com/user-attachments/assets/f3fb01ff-707a-4ce9-b093-5d19bdd2bd74">

Is this just the CDN adjusting and will it fix itself? Or is it really broken? Looks the same in incognito.

Sample URL: https://assets.boolder.com/assets/tailwind-58ec2d1c3c3a40933bd857a5a0ea4ea096eb89c74918fffba8f1e6a838ac173f.css. Maybe the hash is outdated for me?

**Comment by nmondollot** [comment]
Thanks for the report! 😅 

I'm not sure if it's a DNS issue or a SSL certificate issue.
Can you click on an asset in the inspector to see the detailed error? (I can't seem to repro on my machine)

In the meantime I reverted back to the old CDN url.

**Comment by sanderdlm** [comment]
Seems to be a SSL issue 🙂 
```
> curl -i https://assets.boolder.com/assets/tailwind-58ec2d1c3c3a40933bd857a5a0ea4ea096eb89c74918fffba8f1e6a838ac173f.css
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to assets.boolder.com:443 
```
and http://assets.boolder.com/assets/tailwind-58ec2d1c3c3a40933bd857a5a0ea4ea096eb89c74918fffba8f1e6a838ac173f.css does load fine for me.

The revert to the old URL also fixed the site for now 👍

**Comment by nmondollot** [comment]
Good catch!

It may be a problem with [SNI](https://aws.amazon.com/cloudfront/custom-ssl-domains/?nc1=h_ls)
What machine / browser do you use?

**Comment by sanderdlm** [comment]
I'm on a Macbook Pro using Chrome. Firefox also reproduces the issue. On my phone (iOs) it loads the https version just fine 🥲

**Comment by nmondollot** [comment]
That's weird.
SNI has been supported for a long time on these browsers.
But even curl fails in your case, so it's probably not related to your browser.

What's your mac os version?
Are you using a VPN or something like that?

Can you try again in 24h to see if the problems persists?

Thank you for your help!

**Comment by sanderdlm** [comment]
The https URL works fine now 😄 Should've been a bit more patient I guess

**Comment by nmondollot** [comment]
Excellent news!
Thank you for your help 🙏
